### PR TITLE
Add Heka message extension to add GeoIP2 data

### PR DESCRIPTION
**Pull request by trink**

### CODE REVIEW

**Comment by trink** [comment]
@mreid-moz r? on the Issue 233 commit

**Comment by mreid-moz** [comment]
233 commit looks good to me, with one minor complaint that the `get_geo_city` function is now sort of mis-named, since it returns both city and country.

**Comment by trink** [comment]
Yeah I left it that way as it is the query for the city database

**Comment by mreid-moz** [comment]
Ah, that makes sense. 👍

**Pull request merged**
