### PR TITLE
Added derived_kind_costs scheduled query, for cost analysis of all ta…

### PR DESCRIPTION
**Pull request by srfraser**
…sk kinds.

### CODE REVIEW

**Comment by trink** [comment]
This is just a subset of https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/taskcluster/sql/derived_workertype_costs.sql.  Is there a reason that table cannot be used? I thinke we should migrate the test suite costs to use it also and then dump these two tables.

**Comment by srfraser** [comment]
> This is just a subset of https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/taskcluster/sql/derived_workertype_costs.sql. Is there a reason that table cannot be used? I think we should migrate the test suite costs to use it also and then dump these two tables.

It was based on `derived_test_suite_costs`, since I wanted to include more than just tests. It seems we've duplicated some effort, since i didn't see the workertype costs query - I wasn't wanting to query based on worker type, so it didn't make sense to look for that name. 

Assuming it's ok to have a table with large numbers of nulls in, then sure, I can change to the 'workertype' table. I think if I'd caught it earlier I'd suggest a less specific name!

**Comment by trink** [comment]
It is easy enough to rename and alter the schema if necessary at this point.

**Comment by trink** [comment]
Merging to capture the existing state

**Pull request merged**
